package com.AleksiJokilahti.GearHeads.domain;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.springframework.format.annotation.DateTimeFormat;


@Entity
public class Instrument {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;			// unique autogenerated id, not null, not editable
	
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date dateAdded;
	
	@ManyToOne
	@JoinColumn(name = "userid")
	private User owner;
	
	private String brand; 		// brand of the instrument (Fender, Ludwig, etc.)
	private String model; 		// model of the instrument (Stratocaster, LM402, etc.
	private int year;			// year of production
	private String serial;		// serial number of the instrument
	//private String dateAdded;	// date when added to collection
	private double priceBought;	// the price payed for the instrument
	private String condition;	// condition of the instrument
	private String desc;		// description, additional info
	
	@ManyToOne
	@JoinColumn(name = "categoryid")
	private Category category;	// category of the instrument;
	
	// NULL constructor
	public Instrument() {
		super();
		this.id=null;
		this.category = null;
		this.brand = null;
		this.model = null;
		this.year = 0;
		this.serial = null;
		this.dateAdded = null;
		this.priceBought = 0.00;
		this.condition = null;
		this.desc = null;
		this.owner = null;
	}
	
	public Instrument(User owner) {
		super();
		this.id=null;
		this.category = null;
		this.brand = null;
		this.model = null;
		this.year = 0;
		this.serial = null;
		this.dateAdded = null;
		this.priceBought = 0.00;
		this.condition = null;
		this.desc = null;
		this.owner = owner;
	}
	
	public Instrument(Long id, Category category, String brand, String model, int year, String serial, Date dateAdded,
			double priceBought, String condition, String desc, User owner) {
		super();
		this.id = id;
		this.category = category;
		this.brand = brand;
		this.model = model;
		this.year = year;
		this.serial = serial;
		this.dateAdded = dateAdded;
		this.priceBought = priceBought;
		this.condition = condition;
		this.desc = desc;
		this.owner = owner;
	}

	public Instrument(Category category, String brand, String model, int year, String serial, Date dateAdded,
			double priceBought, String condition, String desc, User owner) {
		super();
		this.category = category;
		this.brand = brand;
		this.model = model;
		this.year = year;
		this.serial = serial;
		this.dateAdded = dateAdded;
		this.priceBought = priceBought;
		this.condition = condition;
		this.desc = desc;
		this.owner = owner;
	}
	
	public Instrument(Category category, String brand, String model, int year, String serial, Date dateAdded,
			double priceBought, String condition, String desc) {
		super();
		this.category = category;
		this.brand = brand;
		this.model = model;
		this.year = year;
		this.serial = serial;
		this.dateAdded = dateAdded;
		this.priceBought = priceBought;
		this.condition = condition;
		this.desc = desc;
	}

	//SETTERS
	public void setId(Long id) {
		this.id = id;
	}
	public void setCategory(Category category) {
		this.category = category;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public void setYear(int year) {
		this.year = year;
	}
	public void setSerial(String serial) {
		this.serial = serial;
	}
	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}
	public void setPriceBought(double priceBought) {
		this.priceBought = priceBought;
	}
	public void setCondition(String condition) {
		this.condition = condition;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	
	public void setOwner(User owner) {
		this.owner = owner;
	}

	// GETTERS
	public Long getId() {
		return id;
	}
	public Category getCategory() {
		return category;
	}
	public String getBrand() {
		return brand;
	}
	public String getModel() {
		return model;
	}
	public int getYear() {
		return year;
	}
	public String getSerial() {
		return serial;
	}
	public Date getDateAdded() {
		return dateAdded;
	}
	public String getDateAddedStr() {
		return new SimpleDateFormat("dd.MM.yyyy").format(this.dateAdded);
		
	}
	public double getPriceBought() {
		return priceBought;
	}
	public String getCondition() {
		return condition;
	}
	public String getDesc() {
		return desc;
	}
	
	public User getOwner() {
		return owner;
	}

	@Override
	public String toString() {
		if(this.owner != null) {
			return "Instrument [id=" + id + ", Category=" + category + ", brand=" + brand + ", model=" + model + ", year=" + year + ", serial="
					+ serial + ", dateAdded=" + dateAdded + ", priceBought=" + priceBought + ", condition=" + condition
					+ ", desc=" + desc + "]";
			} else {
		return "Instrument [id=" + id + ", Category=" + category + ", brand=" + brand + ", model=" + model + ", year=" + year + ", serial="
				+ serial + ", dateAdded=" + dateAdded + ", priceBought=" + priceBought + ", condition=" + condition
				+ ", desc=" + desc + ", owner=" + owner.getUsername() + "]";
			}
	}
}
